# Generated by Django 4.0 on 2021-12-25 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Rack number')),
                ('number_of_shelves', models.IntegerField(verbose_name='Number of shelves')),
            ],
            options={
                'verbose_name': 'Rack',
                'verbose_name_plural': 'Racks',
            },
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('article', models.IntegerField(unique=True, verbose_name='Article')),
            ],
            options={
                'verbose_name': 'Shoes',
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Storage Name')),
                ('location', models.CharField(max_length=120, verbose_name='Storage Location')),
            ],
            options={
                'verbose_name': 'Storage',
                'verbose_name_plural': 'Storages',
            },
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Shelf number')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.rack')),
            ],
            options={
                'verbose_name': 'Shelf',
                'verbose_name_plural': 'Shelves',
            },
        ),
        migrations.AddField(
            model_name='rack',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.storage', verbose_name='Storage'),
        ),
    ]
