# Generated by Django 4.0 on 2021-12-25 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoesSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(verbose_name='Size')),
                ('shoes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.shoes', verbose_name='Shoes')),
            ],
        ),
        migrations.RemoveField(
            model_name='shelf',
            name='rack',
        ),
        migrations.AddField(
            model_name='shelf',
            name='storage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.storage', verbose_name='Storage'),
        ),
        migrations.DeleteModel(
            name='Rack',
        ),
    ]
