# Generated by Django 4.0 on 2021-12-25 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_shoessize_remove_shelf_rack_shelf_storage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('article', models.IntegerField(unique=True, verbose_name='Article')),
                ('price', models.IntegerField(verbose_name='Price')),
            ],
            options={
                'verbose_name': 'Product',
            },
        ),
        migrations.CreateModel(
            name='ProductLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.product', verbose_name='Product')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.shelf', verbose_name='Shelf')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.storage', verbose_name='Storage')),
            ],
            options={
                'verbose_name': 'Product location',
                'verbose_name_plural': 'Product locations',
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(verbose_name='Size')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product size',
                'verbose_name_plural': 'Product sizes',
            },
        ),
        migrations.RemoveField(
            model_name='shoessize',
            name='shoes',
        ),
        migrations.DeleteModel(
            name='Shoes',
        ),
        migrations.DeleteModel(
            name='ShoesSize',
        ),
    ]
